
export const qnaData = [
    // General
    { question: "What is VEDA-MOTRIX?", answer: "VEDA-MOTRIX is an AI-powered platform designed to monitor your vehicle's health, predict potential issues, and help you schedule maintenance seamlessly." },
    { question: "How does the AI work?", answer: "Our AI analyzes real-time sensor data from your vehicle to identify patterns and predict potential failures before they happen, ensuring your safety and saving you money." },
    { question: "Is my data secure?", answer: "Absolutely. We use state-of-the-art security measures to protect your vehicle and personal data. All communication is encrypted." },
    { question: "What vehicles are supported?", answer: "We support a wide range of vehicles from major manufacturers like Hero, Mahindra, Tata, and Maruti Suzuki. You can add your vehicle in the dashboard to check compatibility." },
    { question: "How do I add a new vehicle?", answer: "On the Manager Dashboard, you can click the 'Add New Vehicle' button to add a new vehicle to your monitored fleet." },

    // Maintenance & Service
    { question: "What does the 'Health Score' mean?", answer: "The Health Score is a percentage from 0 to 100 that represents your vehicle's overall condition based on our AI analysis. A higher score means better health." },
    { question: "I have a 'Critical' warning. What should I do?", answer: "A 'Critical' warning indicates a high probability of failure. We strongly recommend scheduling a service appointment immediately. You can use the 'Schedule Service' feature on your dashboard." },
    { question: "How often should I service my vehicle?", answer: "We recommend following your manufacturer's service schedule. Our AI will also provide predictive alerts if a service is needed sooner." },
    { question: "What is a 'Predicted Maintenance Alert'?", answer: "This is an alert generated by our AI when it detects a potential issue with a component, such as brake wear or battery degradation, allowing you to fix it proactively." },
    { question: "How accurate are the cost estimates?", answer: "The Predictive Cost Estimator provides a close approximation based on standard labor rates and part costs. The final cost may vary slightly at the service center." },
    { question: "Can I choose my service center?", answer: "Yes, you can select from a list of authorized VEDA-MOTRIX service centers when you schedule your appointment." },
    { question: "How do I book a service appointment?", answer: "Use the 'Schedule Service' card on your dashboard. Select a date, a nearby service center, and an available time slot to confirm your booking." },
    { question: "What if I need to cancel my appointment?", answer: "Please contact the service center directly to cancel or reschedule your appointment. Contact details can be found in your booking confirmation." },
    { question: "Where can I see my past service history?", answer: "Your complete service history is available in the 'Past Service History' table on your vehicle's detailed view page." },
    { question: "How can I rate a service?", answer: "You can rate a past service by clicking the stars in the 'Rating' column of your 'Past Service History' table." },

    // Component-Specific
    { question: "Why is my engine temperature high?", answer: "High engine temperature can be caused by low coolant levels, a faulty thermostat, or a radiator issue. We recommend scheduling a diagnostic check." },
    { question: "What does low oil pressure mean?", answer: "Low oil pressure is a serious issue that can cause engine damage. Stop driving immediately and have your vehicle towed to a service center." },
    { question: "My brake pads need replacing. Is it urgent?", answer: "Yes, worn brake pads can significantly reduce braking performance. It is a critical safety issue and should be addressed as soon as possible." },
    { question: "What's the ideal tire pressure?", answer: "The ideal tire pressure is usually listed on a sticker inside the driver's side door jamb. Maintaining correct pressure ensures safety and fuel efficiency." },
    { question: "My battery voltage seems low. What should I do?", answer: "Low battery voltage could indicate an aging battery or a problem with the alternator. We recommend getting it tested at a service center." },
    { question: "The AI detected high vibration. What could it be?", answer: "High vibration can be caused by unbalanced tires, suspension issues, or engine problems. A professional diagnosis is recommended." },
    { question: "Why is my fuel consumption higher than usual?", answer: "Increased fuel consumption can be due to many factors, including tire pressure, a dirty air filter, or spark plug issues. A general check-up can help identify the cause." },
    { question: "What is 'Suspension Health'?", answer: "Suspension health refers to the condition of your vehicle's shocks, struts, and other components that absorb bumps. Poor suspension health can affect ride comfort and safety." },
    { question: "The 'Sensors' health is low. What does this mean?", answer: "This indicates that one or more vehicle sensors may be malfunctioning. This can affect the accuracy of our AI predictions and should be checked." },
    { question: "What is an 'Anomaly' in my usage analytics?", answer: "An anomaly is a driving event that falls outside of normal parameters, such as sudden high engine vibration or overheating. These events are flagged for your review." },

    // Technical & Account
    { question: "How do I change my password?", answer: "You can change your password in the 'Settings' page, accessible from the user menu in the top right corner." },
    { question: "How do I update my profile information?", answer: "You can update your name and other profile details on the 'Profile' page, accessible from the main navigation menu or the user menu." },
    { question: "Can I have multiple vehicles on one account?", answer: "Yes, you can monitor multiple vehicles from a single user account. The manager role allows adding and viewing all vehicles." },
    { question: "Is there a mobile app?", answer: "A mobile app is currently in development and will be available soon." },
    { question: "Who do I contact for support?", answer: "For any technical issues with the VEDA-MOTRIX platform, please use the 'Help & Support' link in the page footer." },

    // Dashboard features
    { question: "What is the 'Component Health Radar'?", answer: "The radar chart provides a quick, visual overview of the health of your vehicle's key subsystems, such as the engine, brakes, and battery." },
    { question: "What does the 'Vehicle Usage Analytics' chart show?", answer: "This chart displays your driving patterns over the last 30 days, including distance, average speed, and fuel consumption. It also flags any detected anomalies." },
    { question: "How does the 'Service Center Locator' work?", answer: "It shows authorized service centers near your location, along with their user ratings, helping you choose the best option for your service needs." },
    { question: "What is 'RUL'?", answer: "RUL stands for Remaining Useful Life. It is an AI-powered prediction of how long a component or the vehicle itself is expected to last before requiring major repairs or replacement." },
    { question: "What is 'CAPA'?", answer: "CAPA stands for Corrective and Preventive Action. It's a process used in manufacturing to address and eliminate the root causes of failures." },

    // Manufacturing & Executive Dashboards (for managers)
    { question: "What is the 'RCA Similarity Cluster Map'?", answer: "This map on the Manufacturing dashboard groups recurring Root Cause Analysis (RCA) issues by similarity, helping to identify systemic manufacturing or design flaws." },
    { question: "What does the 'CAPA Effectiveness Tracker' measure?", answer: "This metric on the Manufacturing dashboard shows the percentage of Corrective and Preventive Actions (CAPAs) that have successfully resolved an issue without recurrence." },
    { question: "What is the 'AI ROI Dashboard'?", answer: "The Executive Analytics dashboard features an AI ROI (Return on Investment) section that quantifies cost savings, time savings, and breakdown reductions achieved by using VEDA-MOTRIX AI." },
    { question: "What is the 'System Reliability Index (SRI)'?", answer: "The SRI is a key performance indicator on the Executive dashboard that measures the overall uptime and reliability of the VEDA-MOTRIX AI system itself." },
    { question: "What does the 'UEBA Security' view show?", answer: "The UEBA (User and Entity Behavior Analytics) view monitors the behavior of the AI agents themselves, flagging any anomalous or unauthorized actions to ensure system security." },
    { question: "What is the 'Orchestration View'?", answer: "The Orchestration view on the Manager Dashboard visualizes how different AI agents collaborate to analyze data, predict failures, and engage with customers. It also demonstrates the system's self-healing capabilities." },
    { question: "What is the 'Predictive vs. Reactive Maintenance Ratio'?", answer: "This chart on the Executive dashboard shows the shift from unplanned, reactive repairs to planned, predictive maintenance, demonstrating the AI's effectiveness in preventing surprise breakdowns." },
    { question: "What is the 'Policy Compliance Scoreboard'?", answer: "This feature on the Executive dashboard tracks how well service centers are adhering to recommended maintenance protocols and procedures." },
    { question: "What is 'Downtime Reduction Index'?", answer: "This KPI on the Service Analytics dashboard measures the percentage reduction in vehicle downtime (time spent off-road for repairs) compared to a pre-AI baseline." },
    { question: "How does the 'Feedback-to-Action Funnel' work?", answer: "This funnel on the Customer Experience dashboard visualizes the process from receiving customer feedback to creating and resolving a Corrective Action (CAPA) in manufacturing, tracking how user input drives improvements." },
    { question: "What does the 'Service Response Time' chart show?", answer: "This chart on the Customer Experience dashboard tracks the average time it takes from an AI prediction to a scheduled appointment, and from the appointment to the completion of the repair." },
    { question: "What is the 'Complaint Recurrence' chart for?", answer: "This chart on the Customer Experience dashboard identifies how many users report the same issue multiple times, helping to pinpoint ineffective repairs or systemic problems." },
    { question: "What is the 'Failure Chain Graph' on the manufacturing page?", answer: "This graph provides a visual flow from the root cause of a specific failure, through the various sub-causes and effects, to the final resolution and corrective action (CAPA) that was implemented." }
];
